### ISSUE TITLE
Operação get só funciona se os arquivos já estiverem criados

### ISSUE THREAD

**Issue by bcdonadio** [alligo/consul-tls#3]
```
root@certbot:/opt/consul-tls# node index.js get http://consul.service.consul:8500 fq.dn cert key 
/opt/consul-tls/lib/consul-tls.js:28
            throw new Error('File sent as certificate doesn\'t exist');
            ^

Error: File sent as certificate doesn't exist
    at Object.checkParams (/opt/consul-tls/lib/consul-tls.js:28:10)
    at Object.<anonymous> (/opt/consul-tls/index.js:26:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
root@certbot:/opt/consul-tls# touch cert key
root@certbot:/opt/consul-tls# node index.js get http://consul.service.consul:8500 fq.dn cert key
root@certbot:/opt/consul-tls# cat cert
certificado
root@certbot:/opt/consul-tls# cat key 
chave
```

**Comment by luanmuniz** [comment]
Vou implementar
